name:                keyshare-webapi
version:             0.1.0.0
github:              "githubuser/keyshare-webapi"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/keyshare-webapi#readme>

dependencies:
- base >= 4.7 && < 5
- wai >= 3.2.4
- warp >= 3.3.31
- http-types >=0.12.4
- text
- bytestring

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: .
  exposed-modules: 
  - App

executables:
  keyshare-webapi-serve:
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    other-modules:
    - App
    dependencies:
    - keyshare-webapi

tests:
  keyshare-webapi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - keyshare-webapi
